foreman_openscap-0.4.1 requires scap-security-guide
Addressing:
error: Failed dependencies:
	scap-security-guide is needed by
ruby193-rubygem-foreman_openscap-0.4.1-1.el6.noarch